#!/usr/bin/env bash
# Generate PROMPT.md, the flattened single-file fallback for tools with no
# Agent Skills support (T3 Chat, Aider, plain chat UIs).
#
# PROMPT.md is generated, never hand-edited. It contains: a role statement,
# the SKILL.md body (frontmatter stripped, file-map table removed since the
# reference files are not reachable from a chat surface), every required
# reference in workflow order, the PLAN template, and the self-contained
# validator. Local file-read instructions are rewritten to target the inlined
# sections.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SKILL="$REPO_DIR/skills/godplans/SKILL.md"
REFS="$REPO_DIR/skills/godplans/references"
OUT="${GODPLANS_PROMPT_OUT:-$REPO_DIR/PROMPT.md}"

strip_frontmatter() {
  awk 'BEGIN{fm=0} /^---$/{fm++; next} fm!=1{print}' "$1"
}

# The file map points at references/*.md, unreachable from a chat surface;
# drop that section (from its heading to the next H2).
strip_file_map() {
  awk 'BEGIN{skip=0} /^## File map/{skip=1; next} skip && /^## /{skip=0} !skip{print}'
}

# Portable surfaces cannot resolve repository-relative paths. Rewrite only
# the paths that point at content inlined below; project paths such as
# .godplans/PLAN.mdx remain literal because the planning agent can access them.
portable_text() {
  sed \
    -e 's|Each domain has a reference module under `references/`\.|Each domain has an inlined reference module below.|g' \
    -e 's|`references/\([a-z-]*\)\.md`|the inlined \1 reference|g' \
    -e 's|references/\([a-z-]*\)\.md|the inlined \1 reference|g' \
    -e 's|`templates/PLAN\.template\.mdx`|the inlined PLAN template|g' \
    -e 's|templates/PLAN\.template\.mdx|the inlined PLAN template|g' \
    -e 's|`scripts/validate-plan\.sh`|the inlined validator|g' \
    -e 's|scripts/validate-plan\.sh|the inlined validator|g' \
    -e 's|`plan-format\.md`|the inlined plan-format reference|g' \
    -e 's|plan-format\.md|the inlined plan-format reference|g'
}

{
  cat <<'EOF'
# godplans (portable prompt)

You are operating under the godplans skill: a planning superskill that
produces a comprehensive, audit-aware master plan (PLAN.mdx) for a software
project before any code is written. This file is the flattened, single-file
form of the skill for surfaces without Agent Skills support. It includes the
orchestrator, compliance and discovery guidance, all 18 domain modules, the
quality exemplar, the plan-format contract, the PLAN template, and the
self-contained validator in workflow order. No repository-local skill files
are required. When filesystem tools are available, write the inlined validator
byte-for-byte to `.godplans/validate-plan.sh` before validation. The canonical
source lives at https://github.com/hannsxpeter/godplans.

Generated by scripts/build-prompt.sh. Do not edit by hand.

---
EOF
  strip_frontmatter "$SKILL" | strip_file_map | portable_text
  for ref in \
    compliance discovery \
    product architecture stack database security llm ux ui seo code-quality \
    style-genome agent-memory repo build roadmap deploy observe launch \
    exemplar plan-format
  do
    printf '\n\n---\n\n# INLINED REFERENCE: references/%s.md\n\n' "$ref"
    portable_text < "$REFS/$ref.md"
  done
  printf '\n\n---\n\n# INLINED TEMPLATE: templates/PLAN.template.mdx\n\n'
  portable_text < "$REPO_DIR/skills/godplans/templates/PLAN.template.mdx"
  printf '\n\n---\n\n# INLINED VALIDATOR: scripts/validate-plan.sh\n\n```bash\n'
  cat "$REPO_DIR/skills/godplans/scripts/validate-plan.sh"
  printf '\n```\n'
} > "$OUT"

lines=$(wc -l < "$OUT" | tr -d ' ')
echo "Wrote $OUT ($lines lines)"
