#!/usr/bin/env bash
# Generate PROMPT.md, the flattened single-file fallback for tools with no
# Agent Skills support (T3 Chat, Aider, plain chat UIs).
#
# PROMPT.md is generated, never hand-edited. It contains: a role statement,
# the SKILL.md body (frontmatter stripped, file-map table removed since the
# reference files are not reachable from a chat surface), and the three
# load-bearing references inlined (plan-format, discovery, compliance).
# Domain modules are summarized with a pointer to the repo.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SKILL="$REPO_DIR/skills/godplans/SKILL.md"
REFS="$REPO_DIR/skills/godplans/references"
OUT="$REPO_DIR/PROMPT.md"

strip_frontmatter() {
  awk 'BEGIN{fm=0} /^---$/{fm++; next} fm!=1{print}' "$1"
}

# The file map points at references/*.md, unreachable from a chat surface;
# drop that section (from its heading to the next H2).
strip_file_map() {
  awk 'BEGIN{skip=0} /^## File map/{skip=1; next} skip && /^## /{skip=0} !skip{print}'
}

{
  cat <<'EOF'
# godplans (portable prompt)

You are operating under the godplans skill: a planning superskill that
produces a complete, agent-executable master plan (PLAN.mdx) for a software
project before any code is written. This file is the flattened, single-file
form of the skill for surfaces without Agent Skills support. The full skill,
including 18 domain reference modules (product, architecture, roadmap, stack,
repo, build, deploy, observe, launch, security, code-quality, style-genome,
database, llm, seo, ui, ux, agent-memory), lives at
https://github.com/aihxp/godplans. When you cannot read those modules, apply
their discipline as summarized in the method below, and say plainly that the
domain modules were not available in this surface.

Generated by scripts/build-prompt.sh. Do not edit by hand.

---
EOF
  strip_frontmatter "$SKILL" | strip_file_map
  for ref in plan-format discovery compliance; do
    printf '\n\n---\n\n# INLINED REFERENCE: references/%s.md\n\n' "$ref"
    cat "$REFS/$ref.md"
  done
} > "$OUT"

lines=$(wc -l < "$OUT" | tr -d ' ')
echo "Wrote $OUT ($lines lines)"
